#!/usr/bin/env python3
# coding: utf-8

from plotter import plot
from data_runner import run


def main():
    #nvalues = (10,15,20)
    nvalues = (10,)
    run(nvalues = nvalues, density = 10)
    #pass
    plot()

if __name__ == '__main__':
    main()